#!/usr/bin/env python3

import re
import sys
import subprocess

lo = 0    # guaranteed to work
hi = 1500 # first not working
target = sys.argv[1]

while lo + 1 < hi:
    mid = (lo + hi) // 2
    
    try:
        out = subprocess.check_output([
            '/usr/bin/ping',
            '-M', 'do',
            '-c', '5',
            '-w', '10',
            '-i', '0.2',
            '-n',
            '-s', str(mid),
            target,
        ], stderr=subprocess.STDOUT).decode('utf8')

        match = re.search(r'(\d+)% packet loss', out)
        packet_loss = float(match.group(1))

        print('%d: %.1f %% packet loss' % (mid, packet_loss))
        lo = mid

    except subprocess.CalledProcessError:
        print('%d: * * *' % mid)
        hi = mid

print('>>> optimal MTU is %d + 28 = %d' % (lo, lo+28))
